basic_auth_users:
  admin: # your password
tls_server_config:
  cert_file: /etc/prometheus/certs/prometheus.crt
  key_file: /etc/prometheus/certs/prometheus.key
# Create password file (replace 'admin' with desired username)
# htpasswd -Bc prometheus/config/web-config.yml admin
